language: clojure
sudo: required

services:
  - docker

#after_success:
  - lein do clean, ring uberjar
  - docker build -t juhofriman/notv:0.0.1 .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push juhofriman/notv:0.0.1
